using Mass.Core.Devices;

namespace ProUSB.Engine;

public class PxeGenerator : IPxeGenerator
{
    public async Task<string> GeneratePxeBootAsync(PxeConfig config, CancellationToken ct = default)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("#!ipxe");
        sb.AppendLine($"# Generated by Mass Suite for {config.ServerUrl}");
        sb.AppendLine($"set server_url {config.ServerUrl}");
        sb.AppendLine($"set boot_menu {config.BootMenuPath}");
        sb.AppendLine("chain ${server_url}/${boot_menu}");
        
        await Task.CompletedTask;
        return sb.ToString();
    }

    public async Task<bool> ValidateConfigAsync(PxeConfig config)
    {
        await Task.CompletedTask;
        
        if (string.IsNullOrEmpty(config.ServerUrl))
            return false;

        if (string.IsNullOrEmpty(config.BootMenuPath))
            return false;

        return true;
    }
}
